= Noun Service - built from the OpenShift Launch Node.js Booster

IMPORTANT: While you can run and interact with this booster on localhost, it requires that you also have a database installed and configured. This booster runs best when deployed on OpenShift with a PostgreSQL database. For more details on using this booster with a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:http://launcher.fabric8.io/docs/nodejs-runtime.html[Node.js Runtime Guide].

IMPORTANT: This booster requires Node.js 8.x or greater and `npm` 5 or greater.

== Running Locally
NOTE: A PostgreSQL database will need to be running and accepting connections on the standard :5432 IMPORTANT

Following command uses the CentOS based Postgresql 9.6 image from Docker hub:
podman run -d --name insultdb -e POSTGRESQL_USER=user -e POSTGRESQL_PASSWORD=pass -e POSTGRESQL_DATABASE=insultdb -p 5432:5432 docker.io/centos/postgresql-96-centos7


$ node .

== Running the Booster on a Single-node OpenShift Cluster
If you have a single-node OpenShift cluster, such as Minishift or Red Hat Container Development Kit, link:http://launcher.fabric8.io/docs/minishift-installation.html[installed and running], you can also deploy your booster there. A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

To deploy your booster to a running single-node OpenShift cluster:
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer

$ oc new-project MY_PROJECT_NAME

# Ensure that you use the following values for the user name, password and database name when creating your database application.
# The pre-configured values are used in the `credentials-secret.yml` and `deployment.yml` files in the `src/main/fabric8` directory of your booster application project.

$ oc new-app -e POSTGRESQL_USER=user -ePOSTGRESQL_PASSWORD=pass -ePOSTGRESQL_DATABASE=insultdb postgresql:9.6 --name=my-database

# Wait for `my-database` application to be running.

$ npm install && npm run openshift
----


== Interacting with the Booster on a Single-node OpenShift Cluster

To interact with your booster while it's running on a Single-node OpenShift Cluster, you first need to obtain it's URL:

[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route MY_APP_NAME -o jsonpath={$.spec.host}

MY_APP_NAME-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME
----


You can use the form at your application's url or you can use the `curl` command:

.List all entries in the database
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://MY_APP_NAME-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/v1/nouns

[ {
  "id" : 1,
  "noun_text" : "Cherry",
}, {
  "id" : 2,
  "noun_text" : "Apple",
}, {
  "id" : 3,
  "noun_text" : "Banana",
} ]
----

.Retrieve an entry with a specific ID
[source,bash,options="nowrap",subs="attributes+"]
----
curl http://MY_APP_NAME-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/v1/nouns/3

{
  "id" : 3,
  "noun_text" : "Banana",
}
----


.Create a new entry:
[source,bash,options="nowrap",subs="attributes+"]
----
curl -H "Content-Type: application/json" -X POST -d '{"noun_text":"pear"}'  http://MY_APP_NAME-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/v1/nouns

{
  "id" : 4,
  "noun_text" : "pear",
}
----


.Update an Entry
[source,bash,options="nowrap",subs="attributes+"]
----
curl -H "Content-Type: application/json" -X PUT -d '{"noun_text":"pineapple"}'  http://MY_APP_NAME-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/v1/nouns/1

{
  "id" : 1,
  "noun_text" : "pineapple",
}
----


.Delete an Entry:
[source,bash,options="nowrap",subs="attributes+"]
----
curl -X DELETE http://MY_APP_NAME-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/v1/nouns/1
----

NOTE: If you receive an HTTP Error code `503` as a response after executing these commands, it means that the application is not ready yet.

== More Information
You can learn more about this booster and rest of the Node.js runtime in the link:http://launcher.fabric8.io/docs/nodejs-runtime.html[Node.js Runtime Guide].

